"""init

Revision ID: 0a634252f5bd
Revises:
Create Date: 2025-01-04 23:35:03.025203

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa

from application.models import MediaType, PaymentFrequency

# revision identifiers, used by Alembic.
revision = '0a634252f5bd'
down_revision = None
branch_labels = None
depends_on = None

def string_to_date(date_str):
    return datetime.strptime(date_str, '%Y-%m-%d').date()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    media_table = op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('tv', 'film', name='mediatype', create_constraint=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'type', name='_media_title_type_uc')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_title'), ['title'], unique=False)

    subscription_table = op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.String(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('monthly', 'yearly', 'no_change', name='paymentfrequency', create_constraint=True), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('inactive_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_active_date'), ['active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_name'), ['name'], unique=True)

    log_table = op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###

    # Pre-populate tables
    subscriptions = [
        {"name": "Netflix", "cost": "22.99", "payment_frequency": str(PaymentFrequency.monthly), "active_date": string_to_date("2024-12-01")},
        {"name": "Peacock", "cost": "0.00", "payment_frequency": str(PaymentFrequency.yearly), "active_date": string_to_date("2024-12-01")},
        {"name": "Hulu", "cost": "0.99", "payment_frequency": str(PaymentFrequency.monthly), "active_date": string_to_date("2024-12-01")},
        {"name": "Disney+", "cost": "53.33", "payment_frequency": str(PaymentFrequency.yearly), "active_date": string_to_date("2024-12-01")},
        {"name": "Amazon Prime Video", "cost": "139.00", "payment_frequency": str(PaymentFrequency.yearly), "active_date": string_to_date("2024-12-01")},
        {"name": "Crunchyroll", "cost": "0.00", "payment_frequency": str(PaymentFrequency.monthly), "active_date": string_to_date("2024-12-01")},
        {"name": "Xfinity Stream", "cost": "0.00", "payment_frequency": str(PaymentFrequency.yearly), "active_date": string_to_date("2024-12-01")},
        {"name": "Kanopy", "cost": "0.00", "payment_frequency": str(PaymentFrequency.yearly), "active_date": string_to_date("2024-12-01")},
        {"name": "Tubi", "cost": "0.00", "payment_frequency": str(PaymentFrequency.monthly), "active_date": string_to_date("2024-12-01")}
    ]
    op.bulk_insert(subscription_table, subscriptions)

    media = [
        {"title": "How to Die Alone", "type": str(MediaType.tv)},
        {"title": "Abbott Elementary", "type": str(MediaType.tv)},
        {"title": "Laid", "type": str(MediaType.tv)},
        {"title": "Spy x Family", "type": str(MediaType.tv)},
        {"title": "Arcane", "type": str(MediaType.tv)},
        {"title": "When the Phone Rings", "type": str(MediaType.tv)},
        {"title": "Inside Out", "type": str(MediaType.film)},
        {"title": "Inside Out 2", "type": str(MediaType.film)}
    ]
    op.bulk_insert(media_table, media)

    logs = [
        {"date": string_to_date("2025-01-02"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 1},
        {"date": string_to_date("2025-01-02"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 2},
        {"date": string_to_date("2025-01-02"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 3},
        {"date": string_to_date("2025-01-02"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 4},
        {"date": string_to_date("2025-01-03"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 5},
        {"date": string_to_date("2025-01-03"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 6},
        {"date": string_to_date("2025-01-03"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 7},
        {"date": string_to_date("2025-01-03"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 8},
        {"date": string_to_date("2025-01-04"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 9},
        {"date": string_to_date("2025-01-04"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 10},
        {"date": string_to_date("2025-01-05"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 11},
        {"date": string_to_date("2025-01-05"), "subscription_id": 1, "media_id": 6, "season": 1, "episode": 12},
        {"date": string_to_date("2024-12-26"), "subscription_id": 4, "media_id": 7, "season": None, "episode": None},
        {"date": string_to_date("2024-12-26"), "subscription_id": 4, "media_id": 8, "season": None, "episode": None},
        {"date": string_to_date("2025-01-04"), "subscription_id": 3, "media_id": 1, "season": 1, "episode": 1},
        {"date": string_to_date("2025-01-04"), "subscription_id": 3, "media_id": 1, "season": 1, "episode": 2},
        {"date": string_to_date("2025-01-05"), "subscription_id": 3, "media_id": 1, "season": 1, "episode": 3},
        {"date": string_to_date("2025-01-05"), "subscription_id": 3, "media_id": 1, "season": 1, "episode": 4},
        {"date": string_to_date("2024-10-09"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 1},
        {"date": string_to_date("2024-10-16"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 2},
        {"date": string_to_date("2024-10-23"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 3},
        {"date": string_to_date("2024-10-30"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 4},
        {"date": string_to_date("2024-11-06"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 5},
        {"date": string_to_date("2024-11-13"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 6},
        {"date": string_to_date("2024-12-04"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 7},
        {"date": string_to_date("2024-12-04"), "subscription_id": 3, "media_id": 2, "season": 4, "episode": 8},
        {"date": string_to_date("2024-12-25"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 1},
        {"date": string_to_date("2024-12-26"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 2},
        {"date": string_to_date("2024-12-27"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 3},
        {"date": string_to_date("2024-12-28"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 4},
        {"date": string_to_date("2024-12-29"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 5},
        {"date": string_to_date("2024-12-30"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 6},
        {"date": string_to_date("2024-12-31"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 7},
        {"date": string_to_date("2025-01-01"), "subscription_id": 2, "media_id": 3, "season": 1, "episode": 8}
    ]
    op.bulk_insert(log_table, logs)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_log_media_id'))
        batch_op.drop_index(batch_op.f('ix_log_date'))

    op.drop_table('log')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_name'))
        batch_op.drop_index(batch_op.f('ix_subscription_active_date'))

    op.drop_table('subscription')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_title'))

    op.drop_table('media')
    # ### end Alembic commands ###
